import {FC, PropsWithChildren} from 'react';

export const metadata = {
    title: 'Welcome to website',
    description: 'Generated by create-nx-workspace'
};

const EditorLayout: FC<PropsWithChildren> = ({children}) => {
    return <div className="w-full h-full">{children}</div>;
};

export default EditorLayout;
