// This file is generated by icons.js
import type {GrNodeDefDto} from '@/api';
import {
    Bookmark,
    Bot,
    Calculator,
    Clock,
    Cog,
    Cpu,
    File,
    Image,
    Network,
    Text
} from 'lucide-react';
import type {FC} from 'react';

export type GrNodeDefIcon = GrNodeDefDto['icon'];

export const GrNodeDefIcons: Record<GrNodeDefIcon, FC<{className?: string}>> = {
    Bookmark,
    Bot,
    Calculator,
    Clock,
    Cog,
    Cpu,
    File,
    Image,
    Network,
    Text
};
