// This file is auto-generated by @hey-api/openapi-ts

import {createClient, createConfig, type Options} from '@hey-api/client-fetch';
import type {
    ProjectsScaPaginateData,
    ProjectsScaPaginateResponse,
    ProjectsCreateData,
    ProjectsCreateError,
    ProjectsCreateResponse,
    ProjectsCreateValidateData,
    ProjectsCreateValidateError,
    ProjectsCreateValidateResponse,
    ProjectsRemoveData,
    ProjectsRemoveResponse,
    ProjectsScaGetData,
    ProjectsScaGetResponse,
    ProjectsUpdateData,
    ProjectsUpdateError,
    ProjectsUpdateResponse,
    ProjectsUpdateValidateData,
    ProjectsUpdateValidateError,
    ProjectsUpdateValidateResponse,
    EdgesScaPaginateData,
    EdgesScaPaginateResponse,
    EdgesScaCreateData,
    EdgesScaCreateError,
    EdgesScaCreateResponse,
    EdgesScaRemoveData,
    EdgesScaRemoveResponse,
    EdgesScaGetData,
    EdgesScaGetResponse,
    EdgesScaUpdateData,
    EdgesScaUpdateError,
    EdgesScaUpdateResponse,
    NodesScaPaginateData,
    NodesScaPaginateResponse,
    NodesScaCreateData,
    NodesScaCreateError,
    NodesScaCreateResponse,
    NodesScaRemoveData,
    NodesScaRemoveResponse,
    NodesScaGetData,
    NodesScaGetResponse,
    NodesScaUpdateData,
    NodesScaUpdateError,
    NodesScaUpdateResponse,
    WorkspacesScaPaginateData,
    WorkspacesScaPaginateResponse,
    WorkspacesScaCreateData,
    WorkspacesScaCreateError,
    WorkspacesScaCreateResponse,
    WorkspacesScaRemoveData,
    WorkspacesScaRemoveResponse,
    WorkspacesScaGetData,
    WorkspacesScaGetResponse,
    WorkspacesScaUpdateData,
    WorkspacesScaUpdateError,
    WorkspacesScaUpdateResponse,
    SettingsGetData,
    SettingsGetResponse,
    SettingsUpdateData,
    SettingsUpdateResponse,
    SettingsReplaceData,
    SettingsReplaceResponse
} from './types.gen';

export const client = createClient(createConfig());

/**
 * Paginate Project
 */
export const projectsScaPaginate = <ThrowOnError extends boolean = false>(
    options?: Options<ProjectsScaPaginateData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        ProjectsScaPaginateResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects'
    });
};

/**
 * Create a new Project
 */
export const projectsCreate = <ThrowOnError extends boolean = false>(
    options: Options<ProjectsCreateData, ThrowOnError>
) => {
    return (options?.client ?? client).post<
        ProjectsCreateResponse,
        ProjectsCreateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects'
    });
};

/**
 * Validates creation of a ProjectCreate
 */
export const projectsCreateValidate = <ThrowOnError extends boolean = false>(
    options: Options<ProjectsCreateValidateData, ThrowOnError>
) => {
    return (options?.client ?? client).post<
        ProjectsCreateValidateResponse,
        ProjectsCreateValidateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/validates'
    });
};

/**
 * Delete a Project by projectId
 */
export const projectsRemove = <ThrowOnError extends boolean = false>(
    options: Options<ProjectsRemoveData, ThrowOnError>
) => {
    return (options?.client ?? client).delete<
        ProjectsRemoveResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}'
    });
};

/**
 * Get Project by projectId
 */
export const projectsScaGet = <ThrowOnError extends boolean = false>(
    options: Options<ProjectsScaGetData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        ProjectsScaGetResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}'
    });
};

/**
 * Update a Project by projectId
 */
export const projectsUpdate = <ThrowOnError extends boolean = false>(
    options: Options<ProjectsUpdateData, ThrowOnError>
) => {
    return (options?.client ?? client).patch<
        ProjectsUpdateResponse,
        ProjectsUpdateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}'
    });
};

/**
 * Validates updating a ProjectUpdate by projectId
 */
export const projectsUpdateValidate = <ThrowOnError extends boolean = false>(
    options: Options<ProjectsUpdateValidateData, ThrowOnError>
) => {
    return (options?.client ?? client).patch<
        ProjectsUpdateValidateResponse,
        ProjectsUpdateValidateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}/validates'
    });
};

/**
 * Paginate Edge
 */
export const edgesScaPaginate = <ThrowOnError extends boolean = false>(
    options: Options<EdgesScaPaginateData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        EdgesScaPaginateResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/edges'
    });
};

/**
 * Create a new Edge
 */
export const edgesScaCreate = <ThrowOnError extends boolean = false>(
    options: Options<EdgesScaCreateData, ThrowOnError>
) => {
    return (options?.client ?? client).post<
        EdgesScaCreateResponse,
        EdgesScaCreateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/edges'
    });
};

/**
 * Delete a Edge by edgeId
 */
export const edgesScaRemove = <ThrowOnError extends boolean = false>(
    options: Options<EdgesScaRemoveData, ThrowOnError>
) => {
    return (options?.client ?? client).delete<
        EdgesScaRemoveResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/edges/{edgeId}'
    });
};

/**
 * Get Edge by edgeId
 */
export const edgesScaGet = <ThrowOnError extends boolean = false>(
    options: Options<EdgesScaGetData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        EdgesScaGetResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/edges/{edgeId}'
    });
};

/**
 * Update a Edge by edgeId
 */
export const edgesScaUpdate = <ThrowOnError extends boolean = false>(
    options: Options<EdgesScaUpdateData, ThrowOnError>
) => {
    return (options?.client ?? client).patch<
        EdgesScaUpdateResponse,
        EdgesScaUpdateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/edges/{edgeId}'
    });
};

/**
 * Paginate Node
 */
export const nodesScaPaginate = <ThrowOnError extends boolean = false>(
    options: Options<NodesScaPaginateData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        NodesScaPaginateResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/nodes'
    });
};

/**
 * Create a new Node
 */
export const nodesScaCreate = <ThrowOnError extends boolean = false>(
    options: Options<NodesScaCreateData, ThrowOnError>
) => {
    return (options?.client ?? client).post<
        NodesScaCreateResponse,
        NodesScaCreateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/nodes'
    });
};

/**
 * Delete a Node by nodeId
 */
export const nodesScaRemove = <ThrowOnError extends boolean = false>(
    options: Options<NodesScaRemoveData, ThrowOnError>
) => {
    return (options?.client ?? client).delete<
        NodesScaRemoveResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/nodes/{nodeId}'
    });
};

/**
 * Get Node by nodeId
 */
export const nodesScaGet = <ThrowOnError extends boolean = false>(
    options: Options<NodesScaGetData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        NodesScaGetResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/nodes/{nodeId}'
    });
};

/**
 * Update a Node by nodeId
 */
export const nodesScaUpdate = <ThrowOnError extends boolean = false>(
    options: Options<NodesScaUpdateData, ThrowOnError>
) => {
    return (options?.client ?? client).patch<
        NodesScaUpdateResponse,
        NodesScaUpdateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}/workspaces/{workspaceId}/nodes/{nodeId}'
    });
};

/**
 * Paginate Workspace
 */
export const workspacesScaPaginate = <ThrowOnError extends boolean = false>(
    options: Options<WorkspacesScaPaginateData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        WorkspacesScaPaginateResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces'
    });
};

/**
 * Create a new Workspace
 */
export const workspacesScaCreate = <ThrowOnError extends boolean = false>(
    options: Options<WorkspacesScaCreateData, ThrowOnError>
) => {
    return (options?.client ?? client).post<
        WorkspacesScaCreateResponse,
        WorkspacesScaCreateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}/workspaces'
    });
};

/**
 * Delete a Workspace by workspaceId
 */
export const workspacesScaRemove = <ThrowOnError extends boolean = false>(
    options: Options<WorkspacesScaRemoveData, ThrowOnError>
) => {
    return (options?.client ?? client).delete<
        WorkspacesScaRemoveResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}'
    });
};

/**
 * Get Workspace by workspaceId
 */
export const workspacesScaGet = <ThrowOnError extends boolean = false>(
    options: Options<WorkspacesScaGetData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        WorkspacesScaGetResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/projects/{projectId}/workspaces/{workspaceId}'
    });
};

/**
 * Update a Workspace by workspaceId
 */
export const workspacesScaUpdate = <ThrowOnError extends boolean = false>(
    options: Options<WorkspacesScaUpdateData, ThrowOnError>
) => {
    return (options?.client ?? client).patch<
        WorkspacesScaUpdateResponse,
        WorkspacesScaUpdateError,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/projects/{projectId}/workspaces/{workspaceId}'
    });
};

/**
 * Get App settings
 */
export const settingsGet = <ThrowOnError extends boolean = false>(
    options?: Options<SettingsGetData, ThrowOnError>
) => {
    return (options?.client ?? client).get<
        SettingsGetResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        url: '/api/app/settings'
    });
};

/**
 * Update App settings
 */
export const settingsUpdate = <ThrowOnError extends boolean = false>(
    options: Options<SettingsUpdateData, ThrowOnError>
) => {
    return (options?.client ?? client).patch<
        SettingsUpdateResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/app/settings'
    });
};

/**
 * Replace App settings
 */
export const settingsReplace = <ThrowOnError extends boolean = false>(
    options: Options<SettingsReplaceData, ThrowOnError>
) => {
    return (options?.client ?? client).put<
        SettingsReplaceResponse,
        unknown,
        ThrowOnError
    >({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/app/settings'
    });
};
