// This file is auto-generated by @hey-api/openapi-ts

export type ProjectFileDto = {
    /**
     * The unique identifier of the project file
     */
    id: string;
    /**
     * The name of the project (alphanumeric)
     */
    name: string;
    /**
     * The name of the project file
     */
    fileName: string;
    /**
     * The size of the project file in bytes
     */
    size: number;
    /**
     * The folder where the project file is stored
     */
    folder: string;
    /**
     * The path to the project file
     */
    path: string;
    createdAt: string;
};

export type ProjectInstanceWithFileDto = {
    /**
     * ID of the project in memory
     */
    id: string;
    /**
     * The unique identifier of the project file
     */
    fileId: string;
    /**
     * Name of the project
     */
    name: string;
    /**
     * Project file
     */
    file?: ProjectFileDto;
};

export type ProjectInstanceDto = {
    /**
     * ID of the project in memory
     */
    id: string;
    /**
     * The unique identifier of the project file
     */
    fileId: string;
    /**
     * Name of the project
     */
    name: string;
};

export type ProjectFileWithInstanceDto = {
    /**
     * The unique identifier of the project file
     */
    id: string;
    /**
     * The name of the project (alphanumeric)
     */
    name: string;
    /**
     * The name of the project file
     */
    fileName: string;
    /**
     * The size of the project file in bytes
     */
    size: number;
    /**
     * The folder where the project file is stored
     */
    folder: string;
    /**
     * The path to the project file
     */
    path: string;
    createdAt: string;
    /**
     * The unique identifier of the project instance
     */
    instanceId?: string;
    /**
     * Project instance
     */
    instance?: ProjectInstanceDto;
};

export type AppControllerRemoveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerRemoveResponses = {
    200: string;
};

export type AppControllerRemoveResponse =
    AppControllerRemoveResponses[keyof AppControllerRemoveResponses];

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: string;
};

export type AppControllerGetHelloResponse =
    AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type AppControllerPatchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerPatchResponses = {
    200: string;
};

export type AppControllerPatchResponse =
    AppControllerPatchResponses[keyof AppControllerPatchResponses];

export type AppControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerCreateResponses = {
    201: string;
};

export type AppControllerCreateResponse =
    AppControllerCreateResponses[keyof AppControllerCreateResponses];

export type AppControllerPutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerPutResponses = {
    200: string;
};

export type AppControllerPutResponse =
    AppControllerPutResponses[keyof AppControllerPutResponses];

export type ProjectsInstancesControllerRemoveAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/instances';
};

export type ProjectsInstancesControllerRemoveAllResponses = {
    200: unknown;
};

export type ProjectsInstancesControllerIndexData = {
    body?: never;
    path?: never;
    query?: {
        sort?: 'asc' | 'desc';
    };
    url: '/projects/instances';
};

export type ProjectsInstancesControllerIndexResponses = {
    200: Array<ProjectInstanceWithFileDto>;
};

export type ProjectsInstancesControllerIndexResponse =
    ProjectsInstancesControllerIndexResponses[keyof ProjectsInstancesControllerIndexResponses];

export type ProjectsInstancesControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/instances';
};

export type ProjectsInstancesControllerCreateResponses = {
    201: Array<ProjectInstanceWithFileDto>;
};

export type ProjectsInstancesControllerCreateResponse =
    ProjectsInstancesControllerCreateResponses[keyof ProjectsInstancesControllerCreateResponses];

export type ProjectsInstancesControllerRemoveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/instances/{instanceId}';
};

export type ProjectsInstancesControllerRemoveResponses = {
    200: unknown;
};

export type ProjectsInstancesControllerGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/instances/{instanceId}';
};

export type ProjectsInstancesControllerGetResponses = {
    200: ProjectInstanceWithFileDto;
};

export type ProjectsInstancesControllerGetResponse =
    ProjectsInstancesControllerGetResponses[keyof ProjectsInstancesControllerGetResponses];

export type ProjectsFilesControllerIndexData = {
    body?: never;
    path?: never;
    query?: {
        sort?: 'asc' | 'desc';
        sortBy?: 'createdAt' | 'name';
    };
    url: '/projects/files';
};

export type ProjectsFilesControllerIndexResponses = {
    200: Array<ProjectFileWithInstanceDto>;
};

export type ProjectsFilesControllerIndexResponse =
    ProjectsFilesControllerIndexResponses[keyof ProjectsFilesControllerIndexResponses];

export type ProjectsFilesControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/files';
};

export type ProjectsFilesControllerCreateResponses = {
    201: ProjectFileWithInstanceDto;
};

export type ProjectsFilesControllerCreateResponse =
    ProjectsFilesControllerCreateResponses[keyof ProjectsFilesControllerCreateResponses];

export type ProjectsFilesControllerGetData = {
    body?: never;
    path: {
        fileId: string;
    };
    query?: never;
    url: '/projects/files/{fileId}';
};

export type ProjectsFilesControllerGetErrors = {
    /**
     * Project file not found
     */
    404: unknown;
};

export type ProjectsFilesControllerGetResponses = {
    200: ProjectFileWithInstanceDto;
};

export type ProjectsFilesControllerGetResponse =
    ProjectsFilesControllerGetResponses[keyof ProjectsFilesControllerGetResponses];
