import './global.css';
import {ColorSchemeScript} from '@mantine/core';
import {FC, PropsWithChildren} from 'react';
import {AppProvider} from '../src/components/app/AppProvider';

export const metadata = {
    title: 'Welcome to website',
    description: 'Generated by create-nx-workspace'
};

const AppLayout: FC<PropsWithChildren> = ({children}) => {
    return (
        <html lang="en">
            <head>
                <meta charSet="UTF-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <ColorSchemeScript />
            </head>
            <body>
                <AppProvider>{children}</AppProvider>
            </body>
        </html>
    );
};

export default AppLayout;
