import './global.css';
import {ColorSchemeScript, MantineProvider} from '@mantine/core';
import {FC, PropsWithChildren} from 'react';
import {mantineTheme} from '../src/mantine-theme';

export const metadata = {
    title: 'Welcome to website',
    description: 'Generated by create-nx-workspace'
};

const Layout: FC<PropsWithChildren> = ({children}) => {
    return (
        <html lang="en">
            <head>
                <meta charSet="UTF-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <ColorSchemeScript />
            </head>
            <body>
                <MantineProvider theme={mantineTheme}>
                    {children}
                </MantineProvider>
            </body>
        </html>
    );
};

export default Layout;
