import './global.css';
import { FC, PropsWithChildren } from 'react';

export const metadata = {
  title: 'Welcome to website',
  description: 'Generated by create-nx-workspace'
};

const Layout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
    <body>{children}</body>
    </html>
  );
};

export default Layout;
